name: Upstream Sync

on:
  schedule:
    - cron: "15 19 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync_with_upstream:
    name: Sync with Upstream
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # 明确指定token

      - name: Configure Git
        run: |
          git config --global user.name "zxmlysxl"
          git config --global user.email "zxmlysxl@gmail.com"
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n "x-access-token:${{ secrets.GITHUB_TOKEN }}" | base64)"

      - name: Hard Sync with Upstream
        run: |
          # 添加上游仓库（使用token认证）
          git remote add upstream "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MHSanaei/3x-ui.git" || true
          
          # 获取更新
          git fetch upstream main
          
          # 重置本地分支
          git reset --hard upstream/main
          
          # 强制推送（使用token认证）
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main --force

      - name: Handle Failure
        if: failure()
        run: |
          echo "::error::自动同步失败，请手动执行："
          echo "git remote add upstream https://github.com/MHSanaei/3x-ui.git"
          echo "git fetch upstream"
          echo "git reset --hard upstream/main"
          echo "git push origin main --force"
